---

- src: geerlingguy.apache
  version: 3.0.2

- src: geerlingguy.php 
  version: 3.6.3

- src: geerlingguy.mysql 
  version: 2.9.4

- src: geerlingguy.redis
  version: 1.6.0

- src: geerlingguy.repo-epel
  version: 1.2.3
